# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Knowing
subtitle: Knowing Blog
description: Knowing How, Knowing Why!
keywords: knowing, blog
author: Jade
language: zh-CN
timezone: Asia/shanghai

skip_render: README.md

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: git@gitee.com:JadeQYuan/JadeQYuan.git
  branch: master
- type: git
  repo: git@github.com:JadeQYuan/JadeQYuan.github.io.git
  branch: master

# 为hexo-admin添加配置，默认值会被覆盖
metadata:
  description: desc
