# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 乐然 LeRan
subtitle: 乐之者知其所以然
description: 知之者不如好之者，好之者不如乐之者。知其然，知其所以然。
keywords: 乐之者, 知其然
author: Jade
language: zh-CN
timezone: Asia/shanghai

skip_render: README.md

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: git@gitee.com:JadeQYuan/JadeQYuan.git
  branch: master
- type: git
  repo: git@github.com:JadeQYuan/JadeQYuan.github.io.git
  branch: master

# 为hexo-admin添加配置，默认值会被覆盖
metadata:
  description: desc
